version: '3'
services:
    # lightninglabs/bitcoin-core is the base image for bitcoind.
    # The environment variables default values determined on stage of container
    # start within starting script.
    bitcoind:
      image: bitcoind
      container_name: bitcoind
      build:
        context: bitcoind/
      volumes:
        - bitcoin:/data
      environment:
        - RPCAUTH
        - NETWORK
        - BITCOIND_DEBUG
      entrypoint: ["./start-bitcoind.sh"]

    lnd:
      image: lnd
      container_name: lnd
      build:
        context: ../
        dockerfile: dev.Dockerfile
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK
        - CHAIN
        - LND_DEBUG
        - BACKEND=bitcoind
      volumes:
        - lnd:/root/.lnd
      entrypoint: ["./start-lnd.sh"]
      links:
        - "bitcoind:blockchain"
      # ports:
      #   - "10009:10009"
      #   - "9735:9735"

    tapd:
      image: tapd
      container_name: tapd
      build:
        context: tapd/
      environment:
        - NETWORK
      volumes:
        - tapd:/root/.tapd
      entrypoint: ["./start-tapd.sh"]
      links:
        - "lnd:de8f24577b07"
      ports:
        - "10029:10029"
        - "8089:8089"

volumes:
  # bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin:
    driver: local

  # lnd volume is used for persisting lnd application data and chain state
  # during container lifecycle.
  lnd:
    driver: local

  tapd:
    driver: local
